sprint 1/step 1
veraV142/react-burger pull request #5
Opened 2023-05-02 21:07 UTC by veraV142

Промежуточая сдача (sprint-1/step-1)

2023-05-03 04:52 UTC, veraV142 commented
Был случайно закрыт и влит в main предыдущий PR. Пришлось вначале сделать PR с откатом изменений в main, а затем новый PR из той же ветки, что и первый.

2023-05-03 06:06 UTC, andryxxa93 requested changes
**Необходимо исправить**
- Сейчас получается, что под `allData` в `propTypes` может прийти массив любого содержания, но это не так. Необходимо полностью расписать тип ингредиента со всеми его полями (чтобы не дублировать код - сделайте это в отдельном файле) и использовать во всех подобных местах. Вам помогут в этом функции propTypes arrayOf и shape.

2023-05-03 06:06 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.component.jsx
> +    allData: PropTypes.array.isRequired
**Необходимо исправить**
Сейчас получается, что под `allData` может прийти массив любого содержания, но это не так. Необходимо полностью расписать тип ингредиента со всеми его полями (чтобы не дублировать код - сделайте это в отдельном файле) и использовать во всех подобных местах. Вам помогут в этом функции propTypes `arrayOf` и `shape`.

2023-05-04 04:27 UTC, andryxxa93 commented
**Необходимо исправить**
в описании propTypes компонентов нужно указывать .isRequired у пропсов.
`    allData: PropTypes.arrayOf(dataType.isRequired).isRequired`

Промежуточная работа принята, вы можете приступать к финальному этапу сдачи работы!

2023-05-05 20:28 UTC, merged